stages:
  - build
  - test

variables:
  DOCKER_DRIVER: overlay2

build-job:
  stage: build
  script:
    - echo "Собираем проект..."
    - docker --version

test-job:
  stage: test
  script:
    - echo "Тестируем проект..."
    - uname -a
